spring.application.name=CONSTRUMOB
server.port=${SERVER_PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/construmob?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Belem}
spring.datasource.username=${DB_USER:construmob}
spring.datasource.password=${DB_PASSWORD:construmob123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Belem
spring.thymeleaf.cache=false
server.error.include-message=always
