const demands = [
  {id:1,title:'Reforma de cozinha',category:'Reformas',place:'Vila Permanente, Tucuruí',client:'Ana Paula Costa',status:'open',statusLabel:'Aberta',date:'Hoje, 09:42',description:'Troca de revestimento, bancada e pintura da cozinha.'},
  {id:2,title:'Instalação elétrica',category:'Elétrica',place:'Santa Mônica, Tucuruí',client:'Rafael Oliveira',status:'accepted',statusLabel:'Em andamento',date:'Ontem, 16:20',description:'Revisão do quadro e instalação de novos pontos.'},
  {id:3,title:'Pintura externa',category:'Pintura',place:'Centro, Tucuruí',client:'Juliana Mendes',status:'open',statusLabel:'Aberta',date:'12 set, 14:10',description:'Pintura completa da fachada de residência térrea.'},
  {id:4,title:'Manutenção hidráulica',category:'Hidráulica',place:'Jardim Alcobaça, Tucuruí',client:'Carlos Sousa',status:'done',statusLabel:'Finalizada',date:'10 set, 11:30',description:'Correção de vazamento e troca de registros.'},
  {id:5,title:'Construção de muro',category:'Alvenaria',place:'Parque Uirapuru, Tucuruí',client:'Beatriz Lima',status:'open',statusLabel:'Aberta',date:'09 set, 08:50',description:'Muro lateral de 18 metros com portão de acesso.'},
  {id:6,title:'Instalação de piso',category:'Acabamento',place:'Nova Matinha, Tucuruí',client:'Diego Martins',status:'accepted',statusLabel:'Em andamento',date:'08 set, 15:00',description:'Aplicação de porcelanato em sala e corredor.'}
];
const professionals = [{name:'João da Silva',specialty:'Eletricista',rating:'4.9',jobs:'28 serviços',initials:'JS'},{name:'Mariana Alves',specialty:'Pintora profissional',rating:'4.8',jobs:'19 serviços',initials:'MA'},{name:'Carlos Mendes',specialty:'Pedreiro',rating:'4.7',jobs:'34 serviços',initials:'CM'}];
const icons={Reformas:'⌂',Elétrica:'ϟ',Pintura:'◌',Hidráulica:'≈',Alvenaria:'▦',Acabamento:'◇'};
const root=document.getElementById('viewRoot'); const title=document.getElementById('pageTitle'); let activeView='inicio';
const statusClass=s=>s==='open'?'open':s==='accepted'?'accepted':'done';
const demandCard=d=>`<article class="demand-card"><div class="card-top"><div class="category-icon">${icons[d.category]||'◈'}</div><span class="status ${statusClass(d.status)}">${d.statusLabel}</span></div><h3>${d.title}</h3><p>${d.description}</p><div class="meta-row"><span>⌖ ${d.place}</span><span>${d.date}</span></div><div class="card-actions"><button class="secondary-button" data-detail="${d.id}">Ver detalhes</button>${d.status==='open'?`<button class="primary-button" data-accept="${d.id}">Aceitar</button>`:''}${d.status==='accepted'?`<button class="primary-button" data-finish="${d.id}">Finalizar</button>`:''}</div></article>`;
function render(view=activeView){activeView=view; const titles={inicio:'Visão geral',demandas:'Demandas',profissionais:'Profissionais',servicos:'Catálogo de serviços'}; title.textContent=titles[view]; document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); if(view==='inicio') root.innerHTML=homeView(); if(view==='demandas') root.innerHTML=demandasView(); if(view==='profissionais') root.innerHTML=peopleView(); if(view==='servicos') root.innerHTML=servicesView(); bindView();}
function shell(content){return `<div class="content">${content}</div>`}
function homeView(){return shell(`<div class="page-heading"><div><div class="eyebrow">PAINEL DE CONTROLE</div><h1>Bom dia, Marcelo 👋</h1><p>Acompanhe o que está acontecendo no seu marketplace de serviços.</p></div><button class="primary-button" data-modal="demand">+ Publicar nova demanda</button></div><div class="stats"><div class="stat-card"><div class="stat-top">Demandas abertas <span class="stat-icon">◈</span></div><strong>24</strong><span class="trend">↑ 12% <small>vs. mês anterior</small></span></div><div class="stat-card"><div class="stat-top">Profissionais ativos <span class="stat-icon">♙</span></div><strong>86</strong><span class="trend">↑ 8% <small>vs. mês anterior</small></span></div><div class="stat-card"><div class="stat-top">Serviços concluídos <span class="stat-icon">✓</span></div><strong>142</strong><span class="trend">↑ 18% <small>vs. mês anterior</small></span></div><div class="stat-card"><div class="stat-top">Avaliação média <span class="stat-icon">★</span></div><strong>4,8</strong><span class="trend orange">+0,2 <small>vs. mês anterior</small></span></div></div><div class="layout-2"><section class="panel"><div class="panel-header"><h2>Demandas recentes</h2><button class="text-link" data-view="demandas">Ver todas →</button></div><div class="demand-list">${demands.slice(0,4).map(d=>`<div class="demand-row"><div class="category-icon">${icons[d.category]}</div><div class="grow"><strong>${d.title}</strong><small>${d.place} · ${d.client}</small></div><span class="status ${statusClass(d.status)}">${d.statusLabel}</span><button class="text-link" data-detail="${d.id}">Ver</button></div>`).join('')}</div></section><section class="panel"><div class="panel-header"><h2>Atividade recente</h2><span class="eyebrow">AO VIVO</span></div><div class="activity"><div class="activity-item"><div class="activity-dot">✓</div><div><strong>Serviço finalizado</strong><small>Instalação elétrica · há 24 min</small></div></div><div class="activity-item"><div class="activity-dot">★</div><div><strong>Nova avaliação recebida</strong><small>Mariana Alves avaliou com 5 estrelas</small></div></div><div class="activity-item"><div class="activity-dot">+</div><div><strong>Novo profissional cadastrado</strong><small>Pedro Henrique · há 2 h</small></div></div><div class="activity-item"><div class="activity-dot">◈</div><div><strong>Nova demanda publicada</strong><small>Reforma de cozinha · há 3 h</small></div></div></div></section></div>`)}
function demandasView(){return shell(`<div class="page-heading"><div><div class="eyebrow">MURAL DE OPORTUNIDADES</div><h1>Demandas de serviço</h1><p>Encontre, acompanhe e conecte clientes a profissionais validados.</p></div><button class="primary-button" data-modal="demand">+ Publicar demanda</button></div><div class="toolbar"><input id="search" placeholder="Buscar por serviço, localidade ou cliente..."><select id="filter"><option value="all">Todos os status</option><option value="open">Abertas</option><option value="accepted">Em andamento</option><option value="done">Finalizadas</option></select></div><div class="demand-grid" id="demandGrid">${demands.map(demandCard).join('')}</div>`)}
function peopleView(){return shell(`<div class="page-heading"><div><div class="eyebrow">REDE CONSTRUMOB</div><h1>Profissionais</h1><p>Conheça a rede de profissionais cadastrados e validados.</p></div><button class="primary-button" data-toast="Formulário de cadastro em breve">+ Cadastrar profissional</button></div><div class="people-grid">${professionals.map(p=>`<article class="person-card"><div class="card-top"><div class="avatar">${p.initials}</div><span class="status accepted">Validado</span></div><h3>${p.name}</h3><p>${p.specialty}<br><span class="stars">★★★★★</span> ${p.rating} · ${p.jobs}</p><div class="card-actions"><button class="secondary-button" data-toast="Perfil aberto para visualização">Ver perfil</button><button class="primary-button" data-toast="Mensagem enviada">Entrar em contato</button></div></article>`).join('')}</div>`)}
function servicesView(){return shell(`<div class="page-heading"><div><div class="eyebrow">CATÁLOGO</div><h1>Tipos de serviço</h1><p>Serviços disponíveis para publicação de demandas.</p></div><button class="primary-button" data-toast="Cadastro de serviço em breve">+ Novo serviço</button></div><div class="demand-grid">${[['Reformas','12 serviços','Projetos de renovação e melhoria'],['Elétrica','8 serviços','Instalações, manutenção e adequações'],['Pintura','6 serviços','Pintura interna, externa e texturas'],['Hidráulica','7 serviços','Manutenção e novas instalações'],['Alvenaria','9 serviços','Muros, paredes e estruturas'],['Acabamento','11 serviços','Pisos, revestimentos e detalhes']].map(([name,count,desc])=>`<article class="demand-card"><div class="category-icon">${icons[name]}</div><h3>${name}</h3><p>${desc}</p><div class="meta-row"><span>${count}</span><button class="text-link" data-toast="Categoria selecionada">Explorar →</button></div></article>`).join('')}</div>`)}
function bindView(){document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{render(e.dataset.view);document.getElementById('sidebar').classList.remove('open')});document.querySelectorAll('[data-modal]').forEach(e=>e.onclick=()=>openModal(e.dataset.modal));document.querySelectorAll('[data-detail]').forEach(e=>e.onclick=()=>openModal('detail',Number(e.dataset.detail)));document.querySelectorAll('[data-accept]').forEach(e=>e.onclick=()=>mutate(Number(e.dataset.accept),'accepted'));document.querySelectorAll('[data-finish]').forEach(e=>e.onclick=()=>mutate(Number(e.dataset.finish),'done'));document.querySelectorAll('[data-toast]').forEach(e=>e.onclick=()=>toast(e.dataset.toast));const search=document.getElementById('search');const filter=document.getElementById('filter');if(search){const apply=()=>{const q=search.value.toLowerCase(),f=filter.value;document.getElementById('demandGrid').innerHTML=demands.filter(d=>(f==='all'||d.status===f)&&`${d.title} ${d.place} ${d.client}`.toLowerCase().includes(q)).map(demandCard).join('')||'<div class="empty">Nenhuma demanda encontrada.</div>';bindView()};search.oninput=apply;filter.onchange=apply}}
function mutate(id,status){const d=demands.find(x=>x.id===id);if(!d)return;d.status=status;d.statusLabel=status==='accepted'?'Em andamento':'Finalizada';toast(status==='accepted'?'Demanda aceita com sucesso.':'Serviço finalizado com sucesso.');render(activeView)}
function openModal(type,id){const content=document.getElementById('modalContent');if(type==='detail'){const d=demands.find(x=>x.id===id);content.innerHTML=`<div class="eyebrow">DETALHES DA DEMANDA</div><h2>${d.title}</h2><p>${d.description}</p><div class="meta-row"><span>⌖ ${d.place}</span><span>Cliente: ${d.client}</span></div><div class="form-grid"><button class="primary-button" data-toast="Interesse registrado">Tenho interesse nesta demanda</button></div>`}else content.innerHTML='<div class="eyebrow">NOVA DEMANDA</div><h2>Publique uma nova oportunidade</h2><p>Descreva o serviço para encontrar o profissional ideal.</p><form class="form-grid" id="demandForm"><label>Título do serviço<input required name="title" placeholder="Ex.: Reforma de banheiro"></label><label>Categoria<select name="category"><option>Reformas</option><option>Elétrica</option><option>Pintura</option><option>Hidráulica</option><option>Alvenaria</option></select></label><label>Localidade<input required name="place" placeholder="Bairro, cidade"></label><label>Descrição<textarea required name="description" placeholder="Conte um pouco sobre o que precisa..."></textarea></label><button class="primary-button">Publicar demanda</button></form>';document.getElementById('modalBackdrop').hidden=false;document.querySelectorAll('[data-toast]').forEach(e=>e.onclick=()=>{closeModal();toast(e.dataset.toast)});const form=document.getElementById('demandForm');if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);demands.unshift({id:Date.now(),title:f.get('title'),category:f.get('category'),place:f.get('place'),client:'Marcelo Chaves',status:'open',statusLabel:'Aberta',date:'Agora',description:f.get('description')});closeModal();toast('Demanda publicada com sucesso.');render('demandas')}}
function closeModal(){document.getElementById('modalBackdrop').hidden=true}function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');render();
